# -*- coding: utf-8 -*-
"""EvalEVA3_Session7_8k_15epoch_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydQCUSoxGQtWiLm5VTi3e_Zprd5D8nnn
"""

from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 8, 3, padding=1) #28x28| 3
        self.conv2 = nn.Conv2d(8, 8, 3, padding=1) #28x28|5
        self.bn1 = nn.BatchNorm2d(8)  # BatchNorm for 2D input
        self.dropout1 = nn.Dropout(0.05)   # Dropout with a probability of 0.5
        self.pool1 = nn.MaxPool2d(2, 2) #14x14|6
        self.conv3 = nn.Conv2d(8, 8, 3, padding=1) #14x14|10
        self.conv4 = nn.Conv2d(8, 8, 3, padding=1) #14x14|14
        self.dropout2 = nn.Dropout(0.05)   # Dropout with a probability of 0.5
        self.bn2 = nn.BatchNorm2d(8)  # BatchNorm for 2D input
        self.pool2 = nn.MaxPool2d(2, 2) #7x7|15
        self.conv5 = nn.Conv2d(8, 16, 3, padding=1) #5x5|23
        self.conv6 = nn.Conv2d(16, 16, 3, padding=1)#5x5!31
        self.bn3 = nn.BatchNorm2d(16)  # BatchNorm for 2D input
        self.conv7 = nn.Conv2d(16, 10, 3)
        #self.fc = nn.Conv2d(10, 10, kernel_size=1)
        # Global Average Pooling
        self.gap = nn.AdaptiveAvgPool2d((1, 1))  # Output size: (1, 1)

    def forward(self, x):
        x = self.pool1(F.relu(self.conv2(F.relu(self.conv1(x)))))

        x = self.bn1(x)
        x = self.pool2(F.relu(self.conv4(F.relu(self.conv3(x)))))
        x = self.bn2(x)
        x = self.dropout1(x)
        #x = self.bn1(x)
        x = F.relu(self.conv6(F.relu(self.conv5(x))))
        x = self.bn3(x)
        #x = self.dropout2(x)
        x = F.relu(self.conv7(x))
        #x = self.fc(x)
        x = self.gap(x)
        x = x.view(-1, 10)
        return F.log_softmax(x)

#!pip install torchsummary
from torchsummary import summary
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
model = Net().to(device)

summary(model, input_size=(1, 28, 28))

torch.manual_seed(1)
batch_size = 128

kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,transform=transforms.Compose([
                        #transforms.ColorJitter(brightness=0.10, contrast=0.1, saturation=0.10, hue=0.1),
                        #transforms.RandomRotation((-7.0, 7.0), fill=(1,)),
                        transforms.ToTensor(),
                        transforms.Normalize((0.1307,), (0.3081,))
                    ])),
    batch_size=batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, download=True,transform=transforms.Compose([
                        transforms.ToTensor(),
                        transforms.Normalize((0.1307,), (0.3081,))
                    ])),
    batch_size=batch_size, shuffle=True, **kwargs)

#print(train_loader.Data)

from tqdm import tqdm
def train(model, device, train_loader, optimizer, epoch):
    model.train()
    pbar = tqdm(train_loader)
    for batch_idx, (data, target) in enumerate(pbar):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        pbar.set_description(desc= f'loss={loss.item()} batch_id={batch_idx}')



def test(model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += F.nll_loss(output, target, reduction='sum').item()  # sum up batch loss
            pred = output.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    val_acc = 100. * correct / len(test_loader.dataset)

    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.1f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))
    return val_acc

# Variables to track the best model
best_acc = 0.  # Initialize to a high value
from torch.optim.lr_scheduler import StepLR
best_model_path = 'best_model.pth'  # Path to save the model
model = Net().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
scheduler = StepLR(optimizer, step_size=4, gamma=0.1)
#optimizer = optim.Adam(model.parameters(), lr=0.01, betas=(0.9, 0.999), weight_decay=1e-5)
for epoch in range(1, 20):
    train(model, device, train_loader, optimizer, epoch)
    scheduler.step()
    val_acc = test(model, device, test_loader)
    # Check if the current model is the best
    print(f'Epoch: {epoch}')
    if val_acc > best_acc:
        best_acc = val_acc
        print(f'Model saved...')
        torch.save(model.state_dict(), best_model_path)  # Save model state

